### PR TITLE
List children exactly once for ChildSetReconciler

### LINKED ISSUE #481: Determinism of IdentifyChild is confusing
### Describe the bug

* given a set of resources on cluster `oc`
* when I process the KnownChildren (which is `oc`) and produce desired children `dc` (one-to-one for this example)
* then my IdentifyChild should work regardless of on-cluster mutations during the reconcile.

Because the ResourceManager lists and filters the resources via the client again, at the point of `.Manage` - it loads a possibly mutated resource and uses that for that last `IdentifyChild`

This leads to surprising results, because I take the guidance in the docs:
> // Non-deterministic IDs will result in the rapid deletion and creation of child resources.

to mean deterministic for the data passed to this `reconcile`

We were able to find a more "stable" form of identity, however it took a long time to discover the issue because of our assumptions about the data passed into the reconcile.

### PR DESCRIPTION
**Pull request by scothis**
Previously, the ChildSetReconciler would list children once for the set and again for each child being reconciled. At best this was inefficient, at worst it introduced subtile issues when the content of the listing changed over the course of the reconcile.

Now the content of the list from the ChildSetReconciler is reused by each child that is reconciled.

Resolves #481

### CODE REVIEW

**Comment by scothis** [comment]
cc @squeedee

**Review by mamachanko — APPROVED** [review]

File: reconcilers/child.go [hunk 1]
```diff
@@ -306,16 +306,21 @@ func (r *ChildReconciler[T, CT, CLT]) reconcile(ctx context.Context, resource T)
 	c := RetrieveConfigOrDie(ctx)
 
 	actual := r.ChildType.DeepCopyObject().(CT)
-	children := r.ChildListType.DeepCopyObject().(CLT)
-	if err := c.List(ctx, children, r.listOptions(ctx, resource)...); err != nil {
-		return nilCT, err
+	children := RetrieveKnownChildren[CT](ctx)
+	if children == nil {
+		// use existing known children when available, fall back to lookup
```
Comment (squeedee) [inline reconcilers/child.go:311]: Curious to know what situation can lead to this?

Comment (scothis) [reply reconcilers/child.go:311]: It’s the normal path for direct ChildReconciler use. The shortcut is only used by ChildSetReconciler today.

**Comment by squeedee** [comment]
I really like the calledAtMostTimes solution for the test.

File: reconcilers/child.go (hunk 1 above)
Comment (squeedee) [reply reconcilers/child.go:311]: Thanks

**Review by squeedee — APPROVED** [review]
